name: redsun

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    image: redsun-api:${IMAGE_TAG:-latest}
    container_name: redsun-api
    env_file:
      - ${API_ENV_FILE:-apps/api/.env.prod}
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - rs-net

networks:
  rs-net:
    driver: bridge
