[CmdletBinding()]
param(
  [Parameter(Position = 0)]
  [ValidateSet("start", "reset", "stop")]
  [string]$Action = "start",
  [switch]$NoCache,
  [switch]$DebugApi,
  [ValidateRange(1, 600)]
  [int]$HealthTimeoutSeconds = 120
)

$ErrorActionPreference = "Stop"
$pinnedSupabaseVersion = "2.109.1"
$repositoryRoot = $PSScriptRoot
$apiRoot = Join-Path $repositoryRoot "apps/api"
$webRoot = Join-Path $repositoryRoot "apps/web"
$composeFile = Join-Path $apiRoot "docker-compose.yml"
$debugComposeFile = Join-Path $apiRoot "docker-compose.debug.yml"
$apiKeyFile = Join-Path $apiRoot ".env.local.keys"
$webEnvWriter = Join-Path $webRoot "scripts/write-env.js"
$supabaseDbContainer = "supabase_db_redsun-supabase"
$excludedSupabaseServices = "logflare,vector,realtime,edge-runtime,imgproxy,postgrest,supavisor"

function Get-RequiredCommand {
  param(
    [Parameter(Mandatory)]
    [string]$Name,
    [Parameter(Mandatory)]
    [string]$InstallHint
  )

  $command = Get-Command $Name -ErrorAction SilentlyContinue
  if (-not $command) {
    throw "$Name was not found. $InstallHint"
  }

  return $command.Source
}

function Invoke-Checked {
  param(
    [Parameter(Mandatory)]
    [string]$Command,
    [Parameter(Mandatory)]
    [string[]]$Arguments,
    [Parameter(Mandatory)]
    [string]$FailureMessage
  )

  & $Command @Arguments
  if ($LASTEXITCODE -ne 0) {
    throw $FailureMessage
  }
}

function Get-SupabaseStatus {
  param(
    [Parameter(Mandatory)]
    [string]$SupabaseCommand
  )

  $stderrFile = Join-Path ([System.IO.Path]::GetTempPath()) "redsun-status-$([guid]::NewGuid().ToString('N')).stderr"
  $previousPreference = $ErrorActionPreference
  try {
    $ErrorActionPreference = "Continue"
    $output = @(& $SupabaseCommand status --workdir $apiRoot --output env 2> $stderrFile)
    $exitCode = $LASTEXITCODE
  }
  finally {
    $ErrorActionPreference = $previousPreference
  }

  $stderr = if (Test-Path -LiteralPath $stderrFile) {
    (Get-Content -Raw -LiteralPath $stderrFile).Trim()
  } else {
    ""
  }
  Remove-Item -LiteralPath $stderrFile -Force -ErrorAction SilentlyContinue

  if ($exitCode -ne 0) {
    throw "Could not read local Supabase status. $stderr"
  }

  $values = @{}
  foreach ($line in $output) {
    if ([string]$line -match "^\s*([A-Z0-9_]+)=(.*)\s*$") {
      $values[$Matches[1]] = $Matches[2].Trim().Trim('"').Trim("'")
    }
  }

  $publishableKey = @(
    $values["PUBLISHABLE_KEY"],
    $values["ANON_KEY"]
  ) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -First 1

  $serviceRoleKey = @(
    $values["SERVICE_ROLE_KEY"],
    $values["SECRET_KEY"]
  ) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -First 1

  if ([string]::IsNullOrWhiteSpace($publishableKey) -or
      [string]::IsNullOrWhiteSpace($serviceRoleKey)) {
    throw "Supabase status did not contain both a publishable/anon key and a service-role/secret key."
  }

  return @{
    PublishableKey = $publishableKey
    ServiceRoleKey = $serviceRoleKey
  }
}

function Write-GeneratedRuntimeFiles {
  param(
    [Parameter(Mandatory)]
    [hashtable]$Status,
    [Parameter(Mandatory)]
    [string]$NodeCommand
  )

  [System.IO.File]::WriteAllLines(
    $apiKeyFile,
    @(
      "# Generated by local.ps1. Do not commit."
      "SUPABASE_SECRET_KEY=$($Status.ServiceRoleKey)"
    ),
    [System.Text.UTF8Encoding]::new($false)
  )

  $env:APP_ENV = "local"
  $env:BASE_URL = "http://localhost:4200"
  $env:API_BASE_URL = "http://localhost:8080"
  $env:SUPABASE_URL = "http://127.0.0.1:54321"
  $env:SUPABASE_PUBLISHABLE_KEY = $Status.PublishableKey

  Invoke-Checked `
    -Command $NodeCommand `
    -Arguments @($webEnvWriter) `
    -FailureMessage "Could not generate apps/web/public/env.js."
}

function Set-LocalBackendLogin {
  param(
    [Parameter(Mandatory)]
    [string]$DockerCommand
  )

  $provisionSql = @'
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'redsun_dev') THEN
    CREATE ROLE redsun_dev
      NOLOGIN
      NOSUPERUSER
      NOCREATEDB
      NOCREATEROLE
      NOINHERIT
      NOREPLICATION
      NOBYPASSRLS;
  END IF;
END
$$;

ALTER ROLE redsun_dev
  WITH LOGIN
  PASSWORD 'local-redsun-password'
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS;
'@

  Invoke-Checked `
    -Command $DockerCommand `
    -Arguments @(
      "exec", $supabaseDbContainer,
      "psql", "--username", "supabase_admin", "--dbname", "postgres",
      "--set", "ON_ERROR_STOP=1", "--command", $provisionSql
    ) `
    -FailureMessage "Could not provision the restricted local redsun_dev login."
}

function Wait-ForApi {
  $healthUrl = "http://127.0.0.1:8080/actuator/health"
  $timer = [System.Diagnostics.Stopwatch]::StartNew()

  while ($timer.Elapsed.TotalSeconds -lt $HealthTimeoutSeconds) {
    try {
      $response = Invoke-RestMethod -Uri $healthUrl -TimeoutSec 5
      if ($response.status -eq "UP") {
        Write-Host "RedSun API is healthy at $healthUrl."
        return
      }
    }
    catch {
      Start-Sleep -Seconds 2
    }
  }

  throw "The API did not report UP within $HealthTimeoutSeconds seconds."
}

$docker = Get-RequiredCommand "docker" "Install and start Docker Desktop."
$supabase = Get-RequiredCommand "supabase" "Install Supabase CLI $pinnedSupabaseVersion."

$composeArguments = @("compose", "--project-directory", $apiRoot, "--file", $composeFile)
if ($DebugApi) {
  $composeArguments += @("--file", $debugComposeFile)
}

if ($Action -eq "stop") {
  Invoke-Checked $docker ($composeArguments + @("down")) "Could not stop the local API."
  Invoke-Checked $supabase @("stop", "--workdir", $apiRoot) "Could not stop local Supabase."
  Write-Host "Local API and Supabase stopped. Database state was preserved."
  exit 0
}

$node = Get-RequiredCommand "node" "Install the Node version declared in apps/web/package.json."
Invoke-Checked $docker @("info", "--format", "{{.ServerVersion}}") "Docker is unavailable."

$installedSupabaseVersion = ((& $supabase --version 2>&1) | Out-String).Trim()
$versionPattern = "(?<![0-9.])$([regex]::Escape($pinnedSupabaseVersion))(?![0-9.])"
if ($LASTEXITCODE -ne 0 -or $installedSupabaseVersion -notmatch $versionPattern) {
  throw "Supabase CLI $pinnedSupabaseVersion is required. Installed output: $installedSupabaseVersion"
}

Invoke-Checked `
  $supabase `
  @("start", "--workdir", $apiRoot, "--exclude", $excludedSupabaseServices) `
  "Supabase failed to start."

if ($Action -eq "reset") {
  # PostgreSQL roles are cluster-scoped and survive a database reset. Normalize
  # a role left by an older local setup before migrations run as `postgres`.
  Set-LocalBackendLogin $docker
  Write-Warning "Reset destroys local database data and restores the committed migration and seed state."
  Invoke-Checked `
    $supabase `
    @("db", "reset", "--local", "--workdir", $apiRoot) `
    "Supabase database reset failed."
}

$status = Get-SupabaseStatus $supabase
Set-LocalBackendLogin $docker
Write-GeneratedRuntimeFiles $status $node

if ($NoCache) {
  Invoke-Checked `
    $docker `
    ($composeArguments + @("build", "--no-cache", "--pull", "api")) `
    "Could not rebuild the API image."
  $upArguments = $composeArguments + @("up", "--detach", "--no-build", "--force-recreate", "api")
} else {
  $upArguments = $composeArguments + @("up", "--detach", "--build", "--force-recreate", "api")
}

try {
  Invoke-Checked $docker $upArguments "Could not start the local API container."
  Wait-ForApi
}
catch {
  & $docker @composeArguments logs --no-color --tail 200 api
  throw
}

Write-Host "Local services are ready. Start Angular with: cd apps/web; npm run start:local"
