export enum ERuleSystem {
  REDSUN = "REDSUN",
  FIM_DO_MUNDO = "FIM_DO_MUNDO",
  DND = "DND",
  STORYTELLER = "STORYTELLER",
  PATHFINDER = "PATHFINDER",
  BRP = "BRP",
  GURPS = "GURPS",
  SWADE = "SWADE",
  OTHER = "OTHER",
  CUSTOM = "CUSTOM",
}
