spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

supabase:
  url: ${SUPABASE_URL}
  secret-key: ${SUPABASE_SECRET_KEY}
  storage-url: ${SUPABASE_STORAGE_URL}
