package com.rpg.redsunapi.characterSheet;

import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

@NullMarked
public record RedSunSheetResponseDTO(
  @Nullable String id,
  @Nullable String characterId,
  String characterName,
  @Nullable String characterDescription,
  @Nullable String characterImageUrl,
  @Nullable String nature,
  @Nullable String demeanor,
  int strength,
  int dexterity,
  int stamina,
  int presence,
  int empathy,
  int influence,
  int perception,
  int intellect,
  int determination,
  int alertness,
  int sports,
  int intuition,
  int intimidation,
  int subterfuge,
  int leadership,
  int diplomacy,
  @Nullable String talent1Name,
  int talent1Level,
  @Nullable String talent2Name,
  int talent2Level,
  int animalHandling,
  int riding,
  int legerdemain,
  int survival,
  int stealth,
  int athletics,
  int performance,
  int history,
  int religion,
  int language,
  int occultism,
  int investigation,
  int psychology,
  int business,
  @Nullable String calling1Name,
  int calling1Level,
  @Nullable String calling2Name,
  int calling2Level,
  @Nullable String calling3Name,
  int calling3Level,
  @Nullable String calling4Name,
  int calling4Level,
  @Nullable String calling5Name,
  int calling5Level,
  int martialArts,
  int herbalism,
  int rituals,
  int meditation,
  int craft,
  int meleeThrowing,
  int rangedWeapons,
  int unarmed,
  int throwing,
  int exoticWeapons,
  int willpowerMax,
  int willpowerCurrent,
  int impetusMax,
  int impetusCurrent,
  int vitalityDamage,
  @Nullable String experience,
  @Nullable String equipment,
  @Nullable String notes,
  @Nullable String activeRitualsEffects,
  @Nullable String combatManeuvers,
  @Nullable String arsenal,
  @Nullable String learnedRituals,
  @Nullable String craftDetails
) {

  public static RedSunSheetResponseDTO from(RedSunSheet sheet) {
    return new RedSunSheetResponseDTO(
      sheet.getId() != null ? sheet.getId().toString() : null,
      sheet.getCharacterId() != null ? sheet.getCharacterId().toString() : null,
      sheet.getCharacterName(),
      sheet.getCharacterDescription(),
      sheet.getCharacterImageUrl(),
      sheet.nature,
      sheet.demeanor,
      sheet.strength,
      sheet.dexterity,
      sheet.stamina,
      sheet.presence,
      sheet.empathy,
      sheet.influence,
      sheet.perception,
      sheet.intellect,
      sheet.determination,
      sheet.alertness,
      sheet.sports,
      sheet.intuition,
      sheet.intimidation,
      sheet.subterfuge,
      sheet.leadership,
      sheet.diplomacy,
      sheet.talent1Name,
      sheet.talent1Level,
      sheet.talent2Name,
      sheet.talent2Level,
      sheet.animalHandling,
      sheet.riding,
      sheet.legerdemain,
      sheet.survival,
      sheet.stealth,
      sheet.athletics,
      sheet.performance,
      sheet.history,
      sheet.religion,
      sheet.language,
      sheet.occultism,
      sheet.investigation,
      sheet.psychology,
      sheet.business,
      sheet.calling1Name,
      sheet.calling1Level,
      sheet.calling2Name,
      sheet.calling2Level,
      sheet.calling3Name,
      sheet.calling3Level,
      sheet.calling4Name,
      sheet.calling4Level,
      sheet.calling5Name,
      sheet.calling5Level,
      sheet.martialArts,
      sheet.herbalism,
      sheet.rituals,
      sheet.meditation,
      sheet.craft,
      sheet.meleeThrowing,
      sheet.rangedWeapons,
      sheet.unarmed,
      sheet.throwing,
      sheet.exoticWeapons,
      sheet.willpowerMax,
      sheet.willpowerCurrent,
      sheet.impetusMax,
      sheet.impetusCurrent,
      sheet.vitalityDamage,
      sheet.experience,
      sheet.equipment,
      sheet.notes,
      sheet.activeRitualsEffects,
      sheet.combatManeuvers,
      sheet.arsenal,
      sheet.learnedRituals,
      sheet.craftDetails
    );
  }
}
