package com.rpg.redsunapi.characterSheet;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import org.jspecify.annotations.NullMarked;
import org.jspecify.annotations.Nullable;

@NullMarked
@JsonIgnoreProperties(ignoreUnknown = true)
public record RedSunSheetUpsertDTO(
  @NotBlank(message = "Character name is required") String characterName,
  @Nullable String characterDescription,
  @Nullable String nature,
  @Nullable String demeanor,
  @Nullable Integer strength,
  @Nullable Integer dexterity,
  @Nullable Integer stamina,
  @Nullable Integer presence,
  @Nullable Integer empathy,
  @Nullable Integer influence,
  @Nullable Integer perception,
  @Nullable Integer intellect,
  @Nullable Integer determination,
  @Nullable Integer alertness,
  @Nullable Integer sports,
  @Nullable Integer intuition,
  @Nullable Integer intimidation,
  @Nullable Integer subterfuge,
  @Nullable Integer leadership,
  @Nullable Integer diplomacy,
  @Nullable String talent1Name,
  @Nullable Integer talent1Level,
  @Nullable String talent2Name,
  @Nullable Integer talent2Level,
  @Nullable Integer animalHandling,
  @Nullable Integer riding,
  @Nullable Integer legerdemain,
  @Nullable Integer survival,
  @Nullable Integer stealth,
  @Nullable Integer etiquette,
  @Nullable Integer performance,
  @Nullable Integer history,
  @Nullable Integer religion,
  @Nullable Integer language,
  @Nullable Integer occultism,
  @Nullable Integer investigation,
  @Nullable Integer psychology,
  @Nullable Integer business,
  @Nullable String calling1Name,
  @Nullable Integer calling1Level,
  @Nullable String calling2Name,
  @Nullable Integer calling2Level,
  @Nullable String calling3Name,
  @Nullable Integer calling3Level,
  @Nullable String calling4Name,
  @Nullable Integer calling4Level,
  @Nullable String calling5Name,
  @Nullable Integer calling5Level,
  @Nullable Integer martialArts,
  @Nullable Integer herbalism,
  @Nullable Integer rituals,
  @Nullable Integer meditation,
  @Nullable Integer craft,
  @Nullable Integer meleeThrowing,
  @Nullable Integer rangedWeapons,
  @Nullable Integer unarmed,
  @Nullable Integer throwing,
  @Nullable Integer exoticWeapons,
  @Nullable Integer willpowerMax,
  @Nullable Integer willpowerCurrent,
  @Nullable Integer impetusMax,
  @Nullable Integer impetusCurrent,
  @Nullable Integer vitalityDamage,
  @Nullable @Size(max = 500) String experience,
  @Nullable @Size(max = 500) String equipment,
  @Nullable @Size(max = 500) String notes,
  @Nullable @Size(max = 500) String activeRitualsEffects,
  @Nullable @Size(max = 500) String combatManeuvers,
  @Nullable @Size(max = 500) String arsenal,
  @Nullable @Size(max = 500) String learnedRituals,
  @Nullable @Size(max = 500) String craftDetails
) {
}
