[CmdletBinding()]
param(
  [switch]$Reset,
  [int]$HealthTimeoutSeconds = 120
)

$ErrorActionPreference = "Stop"
$minimumSupabaseVersion = [version]"2.108.0"
$maximumExclusiveSupabaseVersion = [version]"3.0.0"
$compatibleSupabaseVersionRange = ">= $minimumSupabaseVersion and < $maximumExclusiveSupabaseVersion"
$excludedSupabaseServices = "logflare,vector,realtime,edge-runtime,imgproxy,postgrest,supavisor"
$supabaseRoot = Split-Path -Parent $PSScriptRoot
$apiRoot = Split-Path -Parent $supabaseRoot
$composeFile = Join-Path -Path $apiRoot -ChildPath "docker-compose.yml"
$containerEnvFile = Join-Path -Path $apiRoot -ChildPath ".env.local.container"
$resetScript = Join-Path -Path $PSScriptRoot -ChildPath "reset-local-supabase.ps1"
$statusFile = $null
$resetEnvFile = $null

function Get-RequiredCommand {
  param(
    [Parameter(Mandatory)]
    [string]$Name,
    [Parameter(Mandatory)]
    [string]$InstallHint
  )

  $command = Get-Command $Name -ErrorAction SilentlyContinue
  if (-not $command) {
    throw "$Name was not found. $InstallHint"
  }

  return $command.Source
}

function Invoke-CheckedCommand {
  param(
    [Parameter(Mandatory)]
    [string]$Command,
    [Parameter(Mandatory)]
    [string[]]$Arguments,
    [Parameter(Mandatory)]
    [string]$FailureMessage
  )

  & $Command @Arguments
  if ($LASTEXITCODE -ne 0) {
    throw $FailureMessage
  }
}

function Get-CompatibleSupabaseVersion {
  param(
    [Parameter(Mandatory)]
    [string]$VersionOutput
  )

  $versionMatch = [regex]::Match(
    $VersionOutput,
    "(?<![0-9.])(?<version>[0-9]+\.[0-9]+\.[0-9]+)(?![-+0-9.])"
  )
  if (-not $versionMatch.Success) {
    throw "Could not parse a stable Supabase CLI version from output: $VersionOutput"
  }

  $version = [version]$versionMatch.Groups["version"].Value
  if ($version -lt $minimumSupabaseVersion -or $version -ge $maximumExclusiveSupabaseVersion) {
    throw "Supabase CLI version $compatibleSupabaseVersionRange is required. Installed output: $VersionOutput"
  }

  return $version
}

function Write-EnvironmentFile {
  param(
    [Parameter(Mandatory)]
    [string]$Path,
    [Parameter(Mandatory)]
    [string]$HostName,
    [Parameter(Mandatory)]
    [string]$ServiceRoleKey
  )

  $values = [ordered]@{
    SERVER_PORT = "8080"
    SPRING_PROFILES_ACTIVE = "local"
    APP_FRONTEND_URL = "http://localhost:4200"
    APP_LOGOUT_REDIRECT = "http://localhost:4200"
    CORS_ALLOWED_ORIGINS = "http://localhost:4200"
    DB_HOST = $HostName
    DB_PORT = "54322"
    DB_NAME = "postgres"
    DB_ADMIN_USER = "postgres"
    DB_ADMIN_PASSWORD = "postgres"
    DB_APP_ROLE = "redsun_dev"
    DB_USER = "redsun_dev"
    DB_PASSWORD = "local-redsun-password"
    SUPABASE_URL = "http://${HostName}:54321"
    SUPABASE_STORAGE_URL = "http://${HostName}:54321/storage/v1/object/public/"
    SUPABASE_SECRET_KEY = $ServiceRoleKey
    SPRING_DATASOURCE_URL = "jdbc:postgresql://${HostName}:54322/postgres?sslmode=disable"
    BREVO_API_KEY = "local-placeholder"
    BREVO_SENDER_EMAIL = "local-placeholder@redsun.invalid"
    BREVO_SENDER_NAME = "RedSun_Local"
    GEMINI_API_KEY = "local-placeholder"
    GEMINI_MODEL = "gemini-3.1-flash-lite"
  }

  $lines = @(
    "# Generated by supabase/scripts/start-local.ps1. Do not commit."
    foreach ($key in $values.Keys) {
      "$key=$($values[$key])"
    }
  )

  [System.IO.File]::WriteAllLines(
    $Path,
    $lines,
    [System.Text.UTF8Encoding]::new($false)
  )
}

function Get-ServiceRoleKey {
  param(
    [Parameter(Mandatory)]
    [string]$SupabaseCommand,
    [Parameter(Mandatory)]
    [string]$Workdir,
    [Parameter(Mandatory)]
    [string]$OutputFile
  )

  $statusErrorFile = "$OutputFile.stderr"
  $previousErrorActionPreference = $ErrorActionPreference
  try {
    # CLI 2.109.x writes informational workdir output to stderr. Capturing
    # stderr with 2>&1 turns that message into a terminating NativeCommandError
    # under Windows PowerShell 5.1 when ErrorActionPreference is Stop.
    $ErrorActionPreference = "Continue"
    $statusOutput = @(
      & $SupabaseCommand status --workdir $Workdir --output env 2> $statusErrorFile
    )
    $statusExitCode = $LASTEXITCODE
  }
  finally {
    $ErrorActionPreference = $previousErrorActionPreference
  }

  $statusErrorText = if (Test-Path -LiteralPath $statusErrorFile) {
    (Get-Content -LiteralPath $statusErrorFile | Out-String).Trim()
  } else {
    ""
  }
  Remove-Item -LiteralPath $statusErrorFile -Force -ErrorAction SilentlyContinue

  if ($statusExitCode -ne 0) {
    $statusText = ($statusOutput | Out-String).Trim()
    $statusDetails = @($statusText, $statusErrorText) |
      Where-Object { -not [string]::IsNullOrWhiteSpace($_) }
    throw "Could not read the local Supabase status. Ensure the stack started successfully.`n$($statusDetails -join [Environment]::NewLine)"
  }

  [System.IO.File]::WriteAllLines(
    $OutputFile,
    [string[]]$statusOutput,
    [System.Text.UTF8Encoding]::new($false)
  )

  foreach ($line in $statusOutput) {
    $text = [string]$line
    if ($text -match "^\s*SERVICE_ROLE_KEY=(.+?)\s*$") {
      return $Matches[1].Trim().Trim('"').Trim("'")
    }
  }

  throw "Supabase status did not contain SERVICE_ROLE_KEY. Verify that a compatible Supabase CLI version ($compatibleSupabaseVersionRange) is installed and the required local services are healthy."
}

function Wait-ForApiHealth {
  param(
    [Parameter(Mandatory)]
    [int]$TimeoutSeconds
  )

  if ($TimeoutSeconds -lt 1) {
    throw "HealthTimeoutSeconds must be at least 1."
  }

  $healthUrl = "http://127.0.0.1:8080/actuator/health"
  $timer = [System.Diagnostics.Stopwatch]::StartNew()
  do {
    try {
      $response = Invoke-RestMethod -Uri $healthUrl -Method Get -TimeoutSec 5
      if ($response.status -eq "UP") {
        Write-Host "RedSun API is healthy at $healthUrl."
        return
      }
    }
    catch {
      # The API may still be starting.
    }

    Start-Sleep -Seconds 3
  } while ($timer.Elapsed.TotalSeconds -lt $TimeoutSeconds)

  throw "The API did not report a healthy status within $TimeoutSeconds seconds."
}

function Show-ApiFailureLogs {
  param(
    [Parameter(Mandatory)]
    [string]$DockerCommand
  )

  Write-Host ""
  Write-Host "Recent API logs:"
  $logs = @(& $DockerCommand compose --project-directory $apiRoot --file $composeFile logs --no-color --tail 200 api 2>&1)
  $logs | ForEach-Object { Write-Host $_ }

  $logText = $logs | Out-String
  if ($logText -match "(?i)(schema-validation|schema validation|missing table|relation .+ does not exist|SchemaManagementException)") {
    Write-Warning "The local database appears uninitialized or incompatible with the API schema. Run this script again with -Reset to explicitly recreate local schema, Auth, Storage, and seed data."
  } else {
    Write-Warning "Inspect the API logs above, confirm port 8080 is available, and verify Docker Desktop has sufficient resources."
  }
}

try {
  $docker = Get-RequiredCommand `
    -Name "docker" `
    -InstallHint "Install and start Docker Desktop: https://docs.docker.com/desktop/"
  $supabase = Get-RequiredCommand `
    -Name "supabase" `
    -InstallHint "Install a stable Supabase CLI version ${compatibleSupabaseVersionRange}: https://supabase.com/docs/guides/local-development/cli/getting-started"

  Invoke-CheckedCommand `
    -Command $docker `
    -Arguments @("info", "--format", "{{.ServerVersion}}") `
    -FailureMessage "Docker is installed but its daemon is unavailable. Start Docker Desktop and retry."
  Invoke-CheckedCommand `
    -Command $docker `
    -Arguments @("compose", "version") `
    -FailureMessage "Docker Compose is unavailable. Install a Docker distribution that includes Compose v2."

  $installedSupabaseVersionOutput = ((& $supabase --version 2>&1) | Out-String).Trim()
  if ($LASTEXITCODE -ne 0) {
    throw "Could not determine the installed Supabase CLI version."
  }
  $installedSupabaseVersion = Get-CompatibleSupabaseVersion `
    -VersionOutput $installedSupabaseVersionOutput
  Write-Host "Using compatible Supabase CLI version $installedSupabaseVersion."

  if ($Reset) {
    $psql = Get-RequiredCommand `
      -Name "psql" `
      -InstallHint "Install PostgreSQL client tools and ensure psql is available on PATH before using -Reset."
    Invoke-CheckedCommand `
      -Command $psql `
      -Arguments @("--version") `
      -FailureMessage "psql was found but could not run. Repair the PostgreSQL client tools installation before using -Reset."
  }

  Write-Host "Starting the required local Supabase services from $apiRoot..."
  Write-Host "Excluding unused services: $excludedSupabaseServices"
  Invoke-CheckedCommand `
    -Command $supabase `
    -Arguments @("start", "--workdir", $apiRoot, "--exclude", $excludedSupabaseServices) `
    -FailureMessage "Supabase failed to start. Review the CLI output and Docker container health."

  $statusFile = Join-Path -Path ([System.IO.Path]::GetTempPath()) -ChildPath "redsun-supabase-status-$([guid]::NewGuid().ToString('N')).env"
  $serviceRoleKey = Get-ServiceRoleKey `
    -SupabaseCommand $supabase `
    -Workdir $apiRoot `
    -OutputFile $statusFile

  Write-EnvironmentFile `
    -Path $containerEnvFile `
    -HostName "host.docker.internal" `
    -ServiceRoleKey $serviceRoleKey
  Write-Host "Generated $containerEnvFile for the API container."

  if ($Reset) {
    $resetEnvFile = Join-Path -Path ([System.IO.Path]::GetTempPath()) -ChildPath "redsun-api-reset-$([guid]::NewGuid().ToString('N')).env"
    Write-EnvironmentFile `
      -Path $resetEnvFile `
      -HostName "127.0.0.1" `
      -ServiceRoleKey $serviceRoleKey

    $powerShellExecutable = (Get-Process -Id $PID).Path
    Write-Warning "Reset requested: recreating local application schema and clearing local Auth, Storage, and seed data."
    Invoke-CheckedCommand `
      -Command $powerShellExecutable `
      -Arguments @("-NoProfile", "-File", $resetScript, "-EnvFile", $resetEnvFile, "-OverrideEnv") `
      -FailureMessage "The explicit local reset failed. Review the SQL error above."
  }

  Write-Host "Building and starting the API container..."
  try {
    Invoke-CheckedCommand `
      -Command $docker `
      -Arguments @("compose", "--project-directory", $apiRoot, "--file", $composeFile, "up", "--detach", "--build") `
      -FailureMessage "Docker Compose could not build or start the API."
    Wait-ForApiHealth -TimeoutSeconds $HealthTimeoutSeconds
  }
  catch {
    Show-ApiFailureLogs -DockerCommand $docker
    throw
  }
}
finally {
  foreach ($temporaryFile in @($resetEnvFile, $statusFile)) {
    if (-not [string]::IsNullOrWhiteSpace($temporaryFile) -and (Test-Path -LiteralPath $temporaryFile)) {
      Remove-Item -LiteralPath $temporaryFile -Force
    }
  }
}
