import {BasicSheetDTO} from "./BasicSheetDTO";

export interface RedSunSheetResponseDTO extends BasicSheetDTO {
  nature: string | null;
  demeanor: string | null;
  strength: number;
  dexterity: number;
  stamina: number;
  presence: number;
  empathy: number;
  influence: number;
  perception: number;
  intellect: number;
  determination: number;
  alertness: number;
  sports: number;
  intuition: number;
  intimidation: number;
  subterfuge: number;
  leadership: number;
  diplomacy: number;
  talent1Name: string | null;
  talent1Level: number;
  talent2Name: string | null;
  talent2Level: number;
  animalHandling: number;
  riding: number;
  legerdemain: number;
  survival: number;
  stealth: number;
  athletics: number;
  performance: number;
  history: number;
  religion: number;
  language: number;
  occultism: number;
  investigation: number;
  psychology: number;
  business: number;
  calling1Name: string | null;
  calling1Level: number;
  calling2Name: string | null;
  calling2Level: number;
  calling3Name: string | null;
  calling3Level: number;
  calling4Name: string | null;
  calling4Level: number;
  calling5Name: string | null;
  calling5Level: number;
  martialArts: number;
  herbalism: number;
  rituals: number;
  meditation: number;
  craft: number;
  meleeThrowing: number;
  rangedWeapons: number;
  unarmed: number;
  willpowerMax: number;
  willpowerCurrent: number;
  impetusMax: number;
  impetusCurrent: number;
  vitalityDamage: number;
  experience: string | null;
  equipment: string | null;
  notes: string | null;
  activeRitualsEffects: string | null;
  combatManeuvers: string | null;
  arsenal: string | null;
  learnedRituals: string | null;
  craftDetails: string | null;
}
