name: API CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  maven-test:
    name: Maven test
    runs-on: ubuntu-latest
    environment: stage

    defaults:
      run:
        working-directory: apps/api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Run tests
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
          SUPABASE_STORAGE_URL: ${{ vars.SUPABASE_STORAGE_URL }}
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          BREVO_SENDER_EMAIL: ${{ vars.BREVO_SENDER_EMAIL }}
          BREVO_SENDER_NAME: ${{ vars.BREVO_SENDER_EMAIL }}
        run: ./mvnw -B -ntp test
